apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  destination:
    namespace: gitea
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gitea
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 10.6.0
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/jhuertom/helmcharts/refs/heads/main/values/gitea.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true