apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  destination:
    namespace: jenkins
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins
    repoURL: https://charts.jenkins.io
    targetRevision: 5.8.67
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/jhuertom/helmcharts/refs/heads/main/values/jenkins.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
