apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.3.1
  share: /mnt/Maria/NFS
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
